name: destiny2_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot for Destiny2 communities.
dependencies:
  dartson: 0.2.7
  destiny2_api:
    git:
      url: https://github.com/pylaligand/destiny2-dart-api-client.git
      ref: effaa03479799638f4332f09385e218a8e929b0f
  heroku_slack_bot:
    git:
      url: https://github.com/pylaligand/heroku-slack-bot.git
      ref: master
  timezone: ^0.5.0-dev-2
dev_dependencies:
  json_schema: 1.0.6
  path: 1.4.2
transformers:
  - dartson
