name: destiny2_slack_bot
author: P.Y. Laligand
version: 0.0.1
description: A Slack bot for Destiny2 communities.
dependencies:
  dartson: 0.2.7
  destiny2_api:
    git:
      url: https://github.com/pylaligand/destiny2-dart-api-client.git
      ref: df4198f4937d0474db19fa099c5048e0c9616c2e
  heroku_slack_bot:
    git:
      url: https://github.com/pylaligand/heroku-slack-bot.git
      ref: 0665a76d5db5113c2af4de17ff1bc44805af17a1
  timezone: ^0.5.0-dev-2
dev_dependencies:
  json_schema: 1.0.6
  path: 1.4.2
transformers:
  - dartson
